# Copyright(C) 2023 Pedro Henrique Penna <pedrohenriquepenna@gmail.com>
# Licensed under the MIT license.

[workspace]
members = [
    "01-hello-world",
    "02-variables",
    "03-primitive-types",
    "04-tuples",
]
